# Generated by Django 4.2.26 on 2025-11-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmotionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "predicted_emotion",
                    models.CharField(max_length=50, verbose_name="Эмоция"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос эмоции",
                "verbose_name_plural": "Запросы эмоций",
            },
        ),
    ]
