# Generated by Django 4.2.26 on 2025-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emotion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionrequest",
            name="algorithm",
            field=models.CharField(default="CatBoostClassifier", max_length=100),
        ),
    ]
