# Generated by Django 4.2.26 on 2025-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emotion", "0002_emotionrequest_algorithm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emotionrequest",
            name="algorithm",
            field=models.CharField(
                default="CatBoostClassifier", max_length=100, verbose_name="Модель"
            ),
        ),
    ]
